#pragma once

#include "lvgl.h"

#define PET_FRAME_W 152
#define PET_FRAME_H 204
#define PET_FRAME_SCALE 768

#define PET_FRAME_IDLE_FIRST 0
#define PET_FRAME_IDLE_COUNT 6
#define PET_FRAME_RUNNING_RIGHT_FIRST 6
#define PET_FRAME_RUNNING_RIGHT_COUNT 8
#define PET_FRAME_RUNNING_LEFT_FIRST 14
#define PET_FRAME_RUNNING_LEFT_COUNT 8
#define PET_FRAME_WAVING_FIRST 22
#define PET_FRAME_WAVING_COUNT 4
#define PET_FRAME_JUMPING_FIRST 26
#define PET_FRAME_JUMPING_COUNT 5
#define PET_FRAME_FAILED_FIRST 31
#define PET_FRAME_FAILED_COUNT 8
#define PET_FRAME_WAITING_FIRST 39
#define PET_FRAME_WAITING_COUNT 6
#define PET_FRAME_RUNNING_FIRST 45
#define PET_FRAME_RUNNING_COUNT 6
#define PET_FRAME_REVIEW_FIRST 51
#define PET_FRAME_REVIEW_COUNT 6
#define PET_FRAME_LOOK_FIRST 57
#define PET_FRAME_LOOK_COUNT 16
#define PET_FRAME_COUNT 73

extern const lv_image_dsc_t *const PET_FRAMES[PET_FRAME_COUNT];
