#!/usr/bin/env python3
"""Generate private RGB565A8 LVGL frames for the ESP32-P4 Codex Pet target.

The input is a Codex v2 8x11 atlas with 192x208 cells. The output is a C
translation unit intentionally kept local/gitignored unless redistribution
rights for the source artwork are explicit.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
from pathlib import Path

CELL_W = 192
CELL_H = 208
CROP_X = 30
CROP_Y = 2
CROP_W = 132
CROP_H = 204
FRAME_W = 396
FRAME_H = 612
FRAME_SPECS = (
    ("IDLE_0", 0, 0),
    ("IDLE_1", 0, 1),
    ("RUNNING_0", 7, 0),
    ("RUNNING_1", 7, 5),
    ("WAITING_0", 6, 0),
    ("WAITING_1", 6, 1),
    ("REVIEW_0", 8, 0),
    ("REVIEW_1", 8, 2),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--spritesheet", required=True, type=Path)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("esp32-p4/main/pet_generated.c"),
    )
    parser.add_argument("--ffmpeg", default="ffmpeg")
    return parser.parse_args()


def decode_rgba(ffmpeg: str, source: Path, row: int, column: int) -> bytes:
    x = column * CELL_W + CROP_X
    y = row * CELL_H + CROP_Y
    vf = (
        f"crop={CROP_W}:{CROP_H}:{x}:{y},"
        f"scale={FRAME_W}:{FRAME_H}:flags=neighbor,format=rgba"
    )
    result = subprocess.run(
        [
            ffmpeg,
            "-loglevel",
            "error",
            "-i",
            str(source),
            "-vf",
            vf,
            "-frames:v",
            "1",
            "-f",
            "rawvideo",
            "-pix_fmt",
            "rgba",
            "-",
        ],
        check=True,
        capture_output=True,
    )
    expected = FRAME_W * FRAME_H * 4
    if len(result.stdout) != expected:
        raise RuntimeError(f"decoded {len(result.stdout)} bytes; expected {expected}")
    return result.stdout


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def rgb565a8_map(rgba: bytes) -> bytes:
    # LVGL RGB565A8 stores all RGB565 pixels first, followed by a full alpha map.
    colours = bytearray()
    alpha = bytearray()
    for offset in range(0, len(rgba), 4):
        r, g, b, a = rgba[offset : offset + 4]
        value = rgb565(r, g, b)
        colours.extend((value & 0xFF, value >> 8))
        alpha.append(a)
    return bytes(colours + alpha)


def format_bytes(values: bytes) -> list[str]:
    return [
        "    " + ", ".join(f"0x{value:02X}" for value in values[i : i + 24]) + ","
        for i in range(0, len(values), 24)
    ]


def main() -> None:
    args = parse_args()
    if not args.spritesheet.is_file():
        raise SystemExit(f"spritesheet not found: {args.spritesheet}")
    if shutil.which(args.ffmpeg) is None:
        raise SystemExit(f"ffmpeg executable not found: {args.ffmpeg}")

    lines = [
        "// Generated by tools/convert_codex_pet_p4.py; do not edit or publish without art rights.",
        '#include "pet_generated.h"',
        "",
    ]
    descriptors: list[str] = []
    total = 0
    for name, row, column in FRAME_SPECS:
        frame = rgb565a8_map(decode_rgba(args.ffmpeg, args.spritesheet, row, column))
        total += len(frame)
        symbol = f"pet_{name.lower()}"
        lines.append(f"static const LV_ATTRIBUTE_MEM_ALIGN uint8_t {symbol}_map[] = {{")
        lines.extend(format_bytes(frame))
        lines.extend(
            [
                "};",
                f"static const lv_image_dsc_t {symbol} = {{",
                "    .header.magic = LV_IMAGE_HEADER_MAGIC,",
                "    .header.cf = LV_COLOR_FORMAT_RGB565A8,",
                "    .header.flags = 0,",
                f"    .header.w = {FRAME_W},",
                f"    .header.h = {FRAME_H},",
                f"    .header.stride = {FRAME_W * 2},",
                f"    .data_size = sizeof({symbol}_map),",
                f"    .data = {symbol}_map,",
                "};",
                "",
            ]
        )
        descriptors.append(f"&{symbol}")

    lines.extend(
        [
            "const lv_image_dsc_t *const PET_FRAMES[PET_FRAME_COUNT] = {",
            "    " + ", ".join(descriptors) + ",",
            "};",
            "",
        ]
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(
        f"wrote {args.output} ({FRAME_W}x{FRAME_H}, {len(FRAME_SPECS)} frames, "
        f"{total} binary image bytes)"
    )


if __name__ == "__main__":
    main()
