#!/usr/bin/env python3
"""Convert a Codex pet atlas into an Arduino Uno-friendly RLE header.

The source atlas is expected to use 192x208 cells and the Codex v2 row order:
0 idle, 6 waiting, 7 running, 8 review. Two frames are selected per state.
The output uses an 8-colour RGB565 palette and one-byte RLE runs so a large
animated pet can fit in the Uno's limited flash without a framebuffer.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
from pathlib import Path
from typing import Iterable

CELL_W = 192
CELL_H = 208
FRAME_SPECS = (
    ("IDLE_0", 0, 0),
    ("IDLE_1", 0, 1),
    ("RUNNING_0", 7, 0),
    ("RUNNING_1", 7, 5),
    ("WAITING_0", 6, 0),
    ("WAITING_1", 6, 1),
    ("REVIEW_0", 8, 0),
    ("REVIEW_1", 8, 2),
)

# Transparent plus seven colours selected for silver/black/red character art.
PALETTE = (
    (0, 0, 0),
    (20, 20, 24),
    (52, 52, 60),
    (105, 105, 112),
    (185, 185, 188),
    (244, 235, 225),
    (105, 20, 35),
    (220, 55, 75),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--spritesheet", required=True, type=Path)
    parser.add_argument(
        "--output", type=Path, default=Path("arduino/CodexPet/pet_generated.h")
    )
    parser.add_argument("--width", type=int, default=86)
    parser.add_argument("--height", type=int, default=94)
    parser.add_argument("--ffmpeg", default="ffmpeg")
    return parser.parse_args()


def nearest_colour(r: int, g: int, b: int) -> int:
    return min(
        range(1, len(PALETTE)),
        key=lambda index: (
            (r - PALETTE[index][0]) ** 2
            + (g - PALETTE[index][1]) ** 2
            + (b - PALETTE[index][2]) ** 2
        ),
    )


def rgb565(colour: tuple[int, int, int]) -> int:
    r, g, b = colour
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def decode_frame(
    ffmpeg: str, source: Path, width: int, height: int, row: int, column: int
) -> list[int]:
    vf = (
        f"crop={CELL_W}:{CELL_H}:{column * CELL_W}:{row * CELL_H},"
        f"scale={width}:{height}:flags=neighbor,format=rgba"
    )
    result = subprocess.run(
        [
            ffmpeg,
            "-loglevel",
            "error",
            "-i",
            str(source),
            "-vf",
            vf,
            "-f",
            "rawvideo",
            "-pix_fmt",
            "rgba",
            "-",
        ],
        check=True,
        capture_output=True,
    )
    expected = width * height * 4
    if len(result.stdout) != expected:
        raise RuntimeError(
            f"decoded {len(result.stdout)} bytes; expected {expected}. "
            "Check the atlas dimensions and selected cells."
        )

    indices: list[int] = []
    for offset in range(0, len(result.stdout), 4):
        r, g, b, alpha = result.stdout[offset : offset + 4]
        indices.append(0 if alpha < 64 else nearest_colour(r, g, b))
    return indices


def encode_rle(indices: Iterable[int]) -> list[int]:
    values = list(indices)
    if not values:
        return []
    output: list[int] = []
    colour = values[0]
    count = 0
    for value in values:
        if value == colour and count < 32:
            count += 1
        else:
            output.append(((count - 1) << 3) | colour)
            colour = value
            count = 1
    output.append(((count - 1) << 3) | colour)
    return output


def format_bytes(values: list[int]) -> list[str]:
    return [
        "  " + ", ".join(f"0x{value:02X}" for value in values[i : i + 24]) + ","
        for i in range(0, len(values), 24)
    ]


def main() -> None:
    args = parse_args()
    if not args.spritesheet.is_file():
        raise SystemExit(f"spritesheet not found: {args.spritesheet}")
    if not 1 <= args.width <= 127 or not 1 <= args.height <= 127:
        raise SystemExit("width and height must be between 1 and 127")
    if shutil.which(args.ffmpeg) is None:
        raise SystemExit(f"ffmpeg executable not found: {args.ffmpeg}")

    lines = [
        "// Generated by tools/convert_codex_pet.py; do not edit manually.",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        f"constexpr uint8_t PET_W = {args.width};",
        f"constexpr uint8_t PET_H = {args.height};",
        "const uint16_t PET_PALETTE[8] PROGMEM = {",
        "  " + ", ".join(f"0x{rgb565(c):04X}" for c in PALETTE) + ",",
        "};",
        "",
    ]

    names: list[str] = []
    total_encoded = 0
    for name, row, column in FRAME_SPECS:
        indices = decode_frame(
            args.ffmpeg,
            args.spritesheet,
            args.width,
            args.height,
            row,
            column,
        )
        encoded = encode_rle(indices)
        total_encoded += len(encoded)
        lines.append(f"const uint8_t PET_{name}[] PROGMEM = {{")
        lines.extend(format_bytes(encoded))
        lines.append("};")
        lines.append(f"constexpr uint16_t PET_{name}_LEN = {len(encoded)};")
        lines.append("")
        names.append(name)

    lines.extend(
        [
            "const uint8_t* const PET_FRAMES[] PROGMEM = {",
            "  " + ", ".join(f"PET_{name}" for name in names) + ",",
            "};",
            "const uint16_t PET_FRAME_LENGTHS[] PROGMEM = {",
            "  " + ", ".join(f"PET_{name}_LEN" for name in names) + ",",
            "};",
            "",
        ]
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(
        f"wrote {args.output} ({args.width}x{args.height}, "
        f"8 frames, {total_encoded} encoded bytes)"
    )


if __name__ == "__main__":
    main()
